version: '3.8'

services:
  faye-server:
    build:
      context: .
      dockerfile: Dockerfile.faye
    container_name: redmine_faye_server
    ports:
      - "9292:9292"
    environment:
      - RACK_ENV=production
    restart: unless-stopped
    networks:
      - redmine-network

networks:
  redmine-network:
    driver: bridge
    name: redmine-network 
